import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "./compononents/Navbar";
import BootstrapClient from "./compononents/BootstrapClient";
import { ReactQueryClientProvider } from "./compononents/ReactQueryClient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {" "}
        <Navbar />{" "}
        <ReactQueryClientProvider>
          {" "}
          {children} <BootstrapClient />{" "}
        </ReactQueryClientProvider>{" "}
      </body>
    </html>
  );
}
